base_station:
  altitude: 51.123
  enable_arp_average: 0
  latitude: 31.359069353
  longitude: 120.714640617
ntrip:
  host: caster.emlid.com
  mountpoint: MP14282
  password: 735sfa
  port: 2101
  username: MP14282
reconnect:
  max_retries: 5
  retry_delay: 5.0
serial:
  baudrate: 115200
  port: /dev/cu.usbserial-027FFD38
